name: My_First_Workflow having space in the name
on: workflow_dispatch
jobs:
  My_First_Job:
    runs-on: ubuntu-latest
    steps:
      - name: My_First_Step
        run: |
          echo "this is my first step!"
          pwd
          ls -l
          echo "END!"
      - name: my_Second_Step
        run: echo "My seconf step!"

