name: My_First_Workflow having space in the name
on: [push, workflow_dispatch]
jobs:
  My_First_Job:
    runs-on: ubuntu-latest
    steps:
      - name: My_First_Step
        run: |
          echo "this is my first step!"
          pwd
          ls -l
          echo "END!"
      - name: my_Second_Step
        run: echo "My seconf step!"

  my_Second_job:
    needs: My_First_Job
    runs-on: ubuntu-latest
    steps:
      - name: second job first step
        run: |
          echo "second job first step!"
          echo "${{toJson(github)}}"

      - name: second job second step
        run: echo "second job second step!"
