name: First_Workflow
on: workflow_dispatch
jobs:
  name: First_job
  runs-on: ubuntu-latest
  steps:
    - name: first_step
      run: echo "My first step!"
    - name: second_step
      run: echo "my second step!"
