name: Workflow
on:
  push:
    branches: main
  pull_request:
    types:
      - opened
      - closed
    branches: main
  workflow_dispatch:

env:
  name: Nandish
  password: abcd123

jobs:
  default_job:
    runs-on: ubuntu-latest
    outputs:
      name:  ${{ steps.abc.outputs }}
    steps: 
    - name: checkout
      uses: actions/checkout@v7
    - name: script
      id: abc
      run: |
        echo "${{ env.name }} and ${{ env.password }}" >> test.txt
        echo "$Script=${{ env.name }} and ${{ env.password }}" >> $GITHUB_OUTPUT
    - name: upload artifact
      if: failure() && steps.abc.outcome == 'failure'
      uses: actions/upload-artifact@v7
      with:
        name: test
        path: test.txt

  second_job:
    needs: default_job
    runs-on: ubuntu-latest
    steps:
      - name: output
        run: echo "${{ needs.default_job.outputs }}"

      - name: download artifact
        uses: actions/download-artifact@v7
        with:
          name: test

      - name: echo vars
        run: echo "${{ vars.name }}"
      - name: echo secrets
        run: echo "${{ secrets.SECRET }}"
      
