name: Second workflow
on:
  pull_request:
    types:
      - opened
      - closed
  push:
  workflow_dispatch:
jobs:
  First_Job:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: | 
          echo "anoedh" >> test.txt
          ehco "ekfhgw" > test.txt

      - name: second step
        uses: actions/upload-artifact@v7
        with:
          name: test
          path: test.txt
  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v7
        with:
          path: test.txt
      - name: echo test file
        run: ehco test.txt
